name: Deploy preview

on:
  workflow_run:
    workflows: ["Build, lint and test"]
    types: [completed]

permissions:
  id-token: write
  actions: read
  contents: read
  security-events: write
  deployments: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        id: get-labels
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "labels=$(gh api /repos/${{ github.repository }}/pulls/${{ github.event.workflow_run.pull_requests[0].number }} --jq '.labels.[].name')" >> "$GITHUB_OUTPUT"
      - run: echo "$labels"
        env:
          labels: ${{ steps.get-labels.outputs.labels }}
      - name: Check if preview label is attached
        if: ${{ !contains(steps.get-labels.outputs.labels, 'allow previews') }}
        run: exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dev-pages
          path: build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
      - name: Unpack
        run: |
          cd build
          tar -xf *.tar.gz
        shell: bash
      - name: Deploy dev-pages
        id: deploy
        uses: timogasda/actions/.github/actions/deploy-static@main
        with:
          role-to-assume: ${{ secrets.AWS_PREVIEW_ROLE_ARN }}
          deployment-bucket: ${{ secrets.AWS_PREVIEW_BUCKET_NAME }}
          source-path: build/lib/static-default
          target-path: dev-pages
          commit-sha: ${{ github.event.workflow_run.head_sha }}
          cloudfront-host: d1ygrbexbkwxpo.cloudfront.net
