name: Deploy preview

on:
  workflow_run:
    workflows: ["Build, lint and test"]
    types: [completed]

permissions:
  id-token: write
  actions: read
  contents: read
  security-events: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - uses: actions/download-artifact@v4
        with:
          name: dev-pages
          path: build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.PREVIEW_ARTIFACTS_TOKEN }}
      - name: Unpack
        run: |
          cd build
          tar -xf *.tar.gz
        shell: bash
      - name: Deploy dev-pages
        id: deploy
        uses: timogasda/actions/.github/actions/deploy-static@main
        with:
          role-to-assume: ${{ secrets.AWS_PREVIEW_ROLE_ARN }}
          deployment-bucket: ${{ secrets.AWS_PREVIEW_BUCKET_NAME }}
          source-path: build/lib/static-default
          target-path: dev-pages
          commit-sha: ${{ github.event.workflow_run.head_sha }}
          cloudfront-host: d1ygrbexbkwxpo.cloudfront.net
